# Generated by Django 2.2 on 2020-04-15 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('M', 'Manillas'), ('C', 'Collares'), ('A', 'Aretes')], default='M', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('I', 'info'), ('S', 'secondary'), ('D', 'danger')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
