# Generated by Django 2.2 on 2020-04-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_item_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('M', 'Manilla'), ('C', 'Collar'), ('A', 'Arete')], max_length=2),
        ),
    ]
