# Generated by Django 2.2 on 2020-04-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200415_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
