# Generated by Django 2.2 on 2020-04-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_item_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default='this is a test text my name is natalia and i am the ceo of naye'),
            preserve_default=False,
        ),
    ]
